SELECT USER FROM DUAL;

SELECT * FROM EMPLOYEE;
SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;


UPDATE DEPARTMENT 
   SET DEPTNAME = '마케팅', FLOOR = 20
 WHERE DEPTNO = 5;
 
DELETE FROM DEPARTMENT WHERE DEPTNO = 6;

DELETE FROM EMPLOYEE WHERE EMPNO = 1005;