SELECT USER FROM DUAL;

SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO FROM EMPLOYEE;
SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;

DELETE FROM EMPLOYEE WHERE EMPNO = 1005;
DELETE FROM DEPARTMENT WHERE DEPTNO = 6;